version: '3.7'

services:
  web:
    image: {{cookiecutter.dockerhub_account}}/{{cookiecutter.project_name}}:latest
    command: gunicorn {{cookiecutter.project_name}}.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - {{cookiecutter.project_name}}_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
  nginx-proxy:
    container_name: nginx-proxy
    image: {{cookiecutter.dockerhub_account}}/{{cookiecutter.project_name}}-nginx:latest
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy
{% if cookiecutter.add_prometheus_and_grafana == 'yes' %}
  prometheus:
    image: {{cookiecutter.dockerhub_account}}/{{cookiecutter.project_name}}-prometheus:latest
    restart: always

  grafana:
    image: {{cookiecutter.dockerhub_account}}/{{cookiecutter.project_name}}-grafana:latest
    restart: always
    volumes:
      - {{cookiecutter.project_name}}_grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    env_file:
      - .env.prod.grafana
{% endif %}
volumes:
  {{cookiecutter.project_name}}_postgres_data:
    external: true
  static_volume:
    external: true
  media_volume:
    external: true
  certs:
    external: true
  html:
    external: true
  vhost:
    external: true
{% if cookiecutter.add_prometheus_and_grafana == 'yes' %}
  {{cookiecutter.project_name}}_grafana:
    external: true
{% endif %} 
